export const template = generateAppTemplate();

function generateAppTemplate(): string {
  // Build the template as a string to avoid Handlebars parsing JSX double-braces
  const lines = [
    `import { useEffect, useState } from 'react';`,
    `import './App.css';`,
    ``,
    `const API_URL = import.meta.env.VITE_API_URL || '{{apiUrl}}';`,
    ``,
    `{{#each pages}}`,
    `function {{pascalCase name}}Page() {`,
    `  return (`,
    `    <div className="page">`,
    `      <h2>{{name}}</h2>`,
    `      <p>{{description}}</p>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `{{/each}}`,
    `function App() {`,
    `  const [health, setHealth] = useState<string>('checking...');`,
    `  const [currentPage, setCurrentPage] = useState<string>('{{#if pages}}{{pages.0.route}}{{else}}/{{/if}}');`,
    ``,
    `  useEffect(() => {`,
    "  fetch(`${API_URL}/health`)",
    `      .then(r => r.json())`,
    `      .then(d => setHealth(d.status))`,
    `      .catch(() => setHealth('offline'));`,
    `  }, []);`,
    ``,
    `  return (`,
    `    <div className="app">`,
    `      <header className="app-header">`,
    `        <h1>{{appName}}</h1>`,
    `        <p className="status">`,
    `          API Status: <span className={health === 'ok' ? 'status-ok' : 'status-error'}>{health}</span>`,
    `        </p>`,
    `      </header>`,
    `      <nav className="app-nav">`,
    `{{#each pages}}`,
    `        <button`,
    `          onClick={() => setCurrentPage('{{route}}')}`,
    `          className={currentPage === '{{route}}' ? 'nav-btn active' : 'nav-btn'}`,
    `        >`,
    `          {{name}}`,
    `        </button>`,
    `{{/each}}`,
    `      </nav>`,
    `      <main>`,
    `{{#each pages}}`,
    `        {currentPage === '{{route}}' && <{{pascalCase name}}Page />}`,
    `{{/each}}`,
    `      </main>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `export default App;`,
  ];
  return lines.join('\n');
}
